### PR TITLE
[EXT-3604] Update React Hooks readme to match public docs

### PR DESCRIPTION
**Pull request by martin3walker**

### CODE REVIEW

**Review by shikaan — COMMENTED** [review]
LGTM, why have we moved links from npm to github?

**Comment by martin3walker** [comment]
It might make more sense just to link the public docs in this repo. Otherwise, we have to update the readme every time we update the docs. Thoughts @andipaetzold?

**Comment by andipaetzold** [comment]
> It might make more sense just to link the public docs in this repo. Otherwise, we have to update the readme every time we update the docs. Thoughts @andipaetzold?

I don't understand why we would need to update the links when the docs change?

In general, I would prefer linking to npm as that's more likely where people come from and will read the CCA docs anyway. But that's just a guess.

**Comment by martin3walker** [comment]
> I don't understand why we would need to update the links when the docs change?
I mean rather than copy pasting the doc app content into the readme, let's just link to that article. That way we only have to keep one thing up to date.

**Comment by andipaetzold** [comment]
I, as a developer, prefer if all necessary information is available in the README formatted using simple markdown. I think that has value over linking to an external page.

**Review by andipaetzold — APPROVED** [review]

**Pull request merged**
