### PR TITLE
chore: Minor clean up on docs and adding github link to npm

### PR DESCRIPTION
**Pull request by kdamball**

### CODE REVIEW

**Comment by fabe** [comment]
Can we also include the docs link in the template?

**Comment by kdamball** [comment]
@fabe does it make sense to include it there considering the video/link seem to help someone before they've bootstrapped while the template is everything after?

**Comment by fabe** [comment]
@kdamball It gives more context about the whole thing and what happened, especially also about the `create-definition` part which happens after the app is bootstrapped.

**Comment by kdamball** [comment]
@fabe added it

**Pull request merged**
