### PR TITLE
feat: [] add dev showcase to app scripts

### PR DESCRIPTION
**Pull request by loweisz**
Adding a success message to the upload script linking to the dev showcase.

Screen Shot 2022-03-03 at 15 21 50

**NOTE:** This can only be merged when the link is ready

### CODE REVIEW

**Comment by loweisz** [comment]
> * https://ctfl.io/submit-app

Great thank you. Would be small enough: 
Screen Shot 2022-03-03 at 15 41 28

**Comment by fabe** [comment]
Maybe just put the links in parenthesis and go without the line break?

**Comment by loweisz** [comment]
> Maybe just put the links in parenthesis and go without the line break?

Like this:
Screen Shot 2022-03-03 at 15 53 26

**Review by fabe — APPROVED** [review]
Looks good, I'd just remove the `:` then!

**Comment by shikaan** [comment]
How do we feel about adding the message also when you publish a new bundle? 

I think it's unlikely you want to put an app in the showcase when it's just been created (might be empty or still not ready to be shared), whereas the promotion of a bundle seems more likely to be a good time for that. WDYT? @fabe @loweisz

**Pull request merged**
