### PR TITLE
fix: adding .env to gitignore

### PR DESCRIPTION
**Pull request by imshuffling**
.env file being generated on `npm run upload`

image

### CODE REVIEW

**Review by kdamball — COMMENTED** [review]
Did you mean to [add it here](https://github.com/contentful/create-contentful-app/blob/master/packages/contentful--cra-template-create-contentful-app/template/gitignore)?

**Comment by imshuffling** [comment]
@kdamball Yup, as per the files changed in the PR :)

**Comment by kdamball** [comment]
@imshuffling we now moved to a monorepo with template data living in `packages/contentful--cra-template-create-contentful-app/template` folder instead of a top level `template/` as the PR suggests.

**Comment by imshuffling** [comment]
@kdamball Ok thanks

**Comment by kdamball** [comment]
@imshuffling if you update your version of create-contentful-app, does it automatically add `.env` to gitignore?

**Comment by imshuffling** [comment]
I've just tried cloning the repo but I dont have permissions to commit to a new branch and push up (to create the PR). How do I go about this?

**Pull request closed without merging**
