### PR TITLE
Fixing parcel errors

### PR DESCRIPTION
**Pull request by kdamball**
bumping ui-ext-sdk version to remove warning errors when developing

### CODE REVIEW

**Comment by Jwhiles** [comment]
fixes #15

**Review by Jwhiles — APPROVED** [review]

**Review by jelz — COMMENTED** [review]
Shouldn't we bump template version too? cc @kdamball

**Comment by kdamball** [comment]
@jelz template version?

**Review by jelz — APPROVED** [review]
Yeah, I've meant the package version. If it's shared then it's good to go ;)

**Pull request merged**
